apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
  namespace: ns-az-training
data:
  prometheus.yml: |-
    global:
      scrape_interval:     5s 
      evaluation_interval: 5s 
    scrape_configs:
     - job_name: 'prometheus'
       static_configs:
       - targets: ['localhost:9090']
     - job_name: 'cool-assur'
       metrics_path: '/q/metrics'
       static_configs:
       - targets: ['cool-assur:80']