name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - develop
      - 'releases/**'
      - 'feature/ci*'
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted #It's linux now on WSL
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.0.0.2'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'
      - name: env
        run: env
      - name: java -version
        run: java -version
      - name: javac -version
        run: javac -version
      - name: chmod
        run: chmod 755 ./mvnw
      # Don't know why it is now mandatory to login to docker first when using jib...
      - name: Log into registry
        run: echo "${{ secrets.DockerHubPassword }}" | docker login registry.hub.docker.com -u ${{ secrets.DockerHubUsername }} --password-stdin
      - name: Build native with Jib and push
        run: ./mvnw -B clean verify -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=native-${GITHUB_REF##*/}'-${quarkus.application.version:latest}' -Dquarkus.container-image.username=${{ secrets.DockerHubUsername }} -Dquarkus.container-image.password=${{ secrets.DockerHubPassword }}
      - name: Send a message to Microsoft Teams
        if: ${{ success() }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
          title: "Nouvelle version ${{ github.event.repository.name }} disponible: ${GITHUB_REF##*/}"
          summary: "Image docker buildee: native-${{GITHUB_REF##*/}}"
          text: "How to run \n ```docker tperdriau/cool-assur:native-${{GITHUB_REF##*/}} pull && docker run --rm --name ca -p 8080:8080 tperdriau/cool-assur:native-${{GITHUB_REF##*/}}```"
          theme_color: " #2b8e18"
          # sections: '[{ "activityTitle": "hello world" }]'
          actions: '[{ "@type": "OpenUri", "name": "dockerHub", "targets": [{ "os": "default", "uri": "https://hub.docker.com/repository/docker/tperdriau/cool-assur" }] }]'