name: testKube

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'feature/kube'
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted #It's linux now on WSL
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.0.0.2'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'
      - name: env
        run: env
      - name: java -version
        run: java -version
      - name: chmod
        run: chmod 755 ./mvnw
      # Don't know why it is now mandatory to login to docker first when using jib...
      - name: Build native with Jib and push
        run: ./mvnw -B clean package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: k8s
          path: "./target/kubernetes/kubernetes.yml"
